module neighborhood

    implicit none




    contains


        pure elemental logical function ball(x, y, z, x0, y0, z0, r)
            !-----------------------------------------------------------------------
            !                Naive search in sphere or radius r 
            !              ******************************************
            ! Transform sequence of integers generated by the function lcg into uniform distribution
            !
            ! INPUT VARIABLES:
            !   x                64 bit integers generated by function lcg
            !
            ! OUTPUT
            !   real             with uniform distribution in interval ]0,1[
            !-----------------------------------------------------------------------

            ! inputs
            real, intent(in) :: x, y, z, x0, y0, z0, r
            
            if ((x-x0)**2 + (y-y0)**2 + (z-z0)**2<=r**2) then
                ball = .True.
            else
                ball = .False.
            end if

        end function ball



end module neighborhood

program test_neighborhood
    use neighborhood
    implicit none

    real :: x(5) = [1,2,3,4,5]
    real :: y(5) = [1,2,3,4,5]
    real :: z(5) = [0,0,0,0,0]

    print *,  ball (x, y, z, x0 = 1., y0 = 1., z0 =1., r =2.)
end program